name: ejdb2_dart
description: Embeddable JSON Database engine http://ejdb.org Dart binding
version: 1.0.0
homepage: https://github.com/Softmotions/ejdb
author: Adamansky Anton <adamansky@gmail.com>
license: MIT

environment:
  sdk: '>=2.2.0 <3.0.0'
